<#
  PCC new-project bootstrap (COCKPIT_ROADMAP #18).

  Scaffolds a brand-new project "the PCC way" so every project starts identical:
  the cockpit app, the self-contained detector/lifecycle/handoff scripts, fresh
  declared state (lifecycle pinned at 'define', generic boundaries), and starter
  brief/rules/decisions. Then optionally git-inits it.

  Deterministic: file copies + templated text, no LLM. Read-only against THIS
  repo (the reference implementation); only writes under -Target.

  Usage:
    pwsh -File scripts/bootstrap-project.ps1 -Target C:\path\to\new-project -Name "My Project"
    (add -Force to write into a non-empty folder; -NoGit to skip git init)
#>
param(
  [Parameter(Mandatory = $true)][string]$Target,
  [Parameter(Mandatory = $true)][string]$Name,
  [string]$Blueprint,
  [switch]$Force,
  [switch]$NoGit,
  [switch]$NoInbox   # skip the scaffolded-inbox drop (the caller registers the project directly)
)

$ErrorActionPreference = 'Stop'
$src = Split-Path -Parent $PSScriptRoot

# Optional blueprint (from the chat intake, reusing CCB's wizard shape). When
# present, the brief and first decision are filled from it instead of the
# generic template.
$bp = $null
if ($Blueprint) {
  if (-not (Test-Path -LiteralPath $Blueprint -PathType Leaf)) { Write-Error "Blueprint not found: $Blueprint"; exit 1 }
  try { $bp = Get-Content -Raw -LiteralPath $Blueprint | ConvertFrom-Json } catch { Write-Error "Blueprint is not valid JSON: $($_.Exception.Message)"; exit 1 }
}

# --- validate target ---
if (Test-Path -LiteralPath $Target) {
  $existing = @(Get-ChildItem -LiteralPath $Target -Force)
  if ($existing.Count -gt 0 -and -not $Force) {
    Write-Error "Target '$Target' is not empty. Use -Force to write into it anyway."
    exit 1
  }
} else {
  New-Item -ItemType Directory -Path $Target -Force | Out-Null
}
$Target = (Resolve-Path -LiteralPath $Target).Path
Write-Output "Bootstrapping '$Name' into $Target"

function Ensure-Dir([string]$p) { if (-not (Test-Path -LiteralPath $p)) { New-Item -ItemType Directory -Path $p -Force | Out-Null } }
function Copy-File([string]$rel) {
  $from = Join-Path $src $rel
  if (-not (Test-Path -LiteralPath $from)) { Write-Output "  (skip, missing: $rel)"; return }
  $to = Join-Path $Target $rel
  Ensure-Dir (Split-Path -Parent $to)
  Copy-Item -LiteralPath $from -Destination $to -Force
  Write-Output "  + $rel"
}

# --- 1. the cockpit app, WITHOUT node_modules (large; regenerated by npm install)
#        and without the dev repo's local verification record. Excluded up front
#        rather than copy-then-delete, so bootstrap stays fast. ---
Write-Output "Copying app/ (excluding node_modules) ..."
$appSrc = Join-Path $src 'app'
$appDst = Join-Path $Target 'app'
Ensure-Dir $appDst
Get-ChildItem -LiteralPath $appSrc -Force | Where-Object { $_.Name -ne 'node_modules' } | ForEach-Object {
  Copy-Item -LiteralPath $_.FullName -Destination $appDst -Recurse -Force
}
$lv = Join-Path $appDst 'last-verification.txt'
if (Test-Path -LiteralPath $lv) { Remove-Item -LiteralPath $lv -Force }

# --- 2. the full cockpit engine, copied WHOLESALE so every project is born
#        identical and bulletproof-by-default (DECISION-106). A hand-picked script
#        list silently drifted: new scripts (e.g. the lifecycle-advance gate,
#        high-stakes/doctor) AND the CI + pre-commit guardrails never got added, so
#        scaffolded projects had dead features and no test gate. Copying the whole
#        engine — every detector/lifecycle/verify/backup script, their schemas, the
#        CI workflow, and the pre-commit test gate — fixes that at the root and
#        keeps any FUTURE script travel automatically, no list to maintain. ---
Write-Output "Copying the cockpit engine (scripts, schemas, CI workflow, pre-commit gate) ..."
foreach ($dir in @('scripts', 'schemas', '.github', '.githooks')) {
  $from = Join-Path $src $dir
  if (Test-Path -LiteralPath $from) {
    Copy-Item -LiteralPath $from -Destination $Target -Recurse -Force
    Write-Output "  + $dir/ (whole)"
  } else {
    Write-Output "  (skip, missing: $dir/)"
  }
}

# --- 3. config / rules ---
Copy-File 'CLAUDE.md'
Copy-File 'AGENTS.md'
Copy-File '.gitignore'
Copy-File 'docs/BACKUP_POLICY.md'   # the mandatory backup policy CLAUDE.md + the copied backup script reference
Copy-File 'docs/DECISION_AND_CHANGE_STANDARD.md'  # the locked decision + change-rollout standard (ADR format + Confirmation/Engagement)
Copy-File 'docs/TRUST_CALIBRATION.md'             # owner-facing "how much to trust a done" guide
Copy-File 'docs/specs/README.md'                  # the lean feature-spec standard + template

# --- 4. generic declared state (lifecycle model + thresholds copied; state fresh) ---
Copy-File '.cockpit/state/lifecycle-model.json'
# The model switcher list is generic (no project-specific data), so COPY the current one rather
# than templating a stale copy — every new project is born with the same up-to-date model list and
# default the home cockpit has (fix for under-provisioning: children were born without models.json
# and fell back to a hard-coded single-model list the owner couldn't edit).
Copy-File '.cockpit/state/models.json'
# NOTE: bloat-thresholds.json is NOT copied from PCC (soak fix F10). PCC's globs point
# at PCC's own engine (app/, scripts/), so a copied config made the child flag the
# copied engine as the owner's bloat. A product-scoped config is generated below.
Ensure-Dir (Join-Path $Target '.cockpit/result/detections')
Ensure-Dir (Join-Path $Target '.cockpit/logs')

$stamp = (Get-Date).ToString('yyyy-MM-ddTHH:mm:sszzz')

Set-Content -LiteralPath (Join-Path $Target '.cockpit/state/lifecycle-state.json') -Encoding utf8 -Value (@"
{
  "lane": "main",
  "current_stage": "define",
  "note": "New project bootstrapped by PCC. Start by defining the goal and rough scope. Set deliberately, not inferred.",
  "updated_at": "$stamp"
}
"@)

Set-Content -LiteralPath (Join-Path $Target '.cockpit/state/app-build-scope.json') -Encoding utf8 -Value (@"
{
  "scope_id": "main",
  "title": "$Name - allowed-change boundary",
  "authorized_by": "bootstrap",
  "plain_language": {
    "what_this_is": "The honest list of what work on this project is allowed to change, so the drift signal has a real boundary instead of guessing. Edit allowed_globs as the project takes shape.",
    "must_not_change": "Anything not covered below should be a deliberate decision, not an accident."
  },
  "compare_baseline": "pcc-baseline",
  "allowed_globs": ["product/**", "app/**", "scripts/**", "docs/**", "PROJECT.md", "CLAUDE.md", "AGENTS.md", ".gitignore", ".cockpit/**"],
  "updated_at": "$stamp"
}
"@)

Set-Content -LiteralPath (Join-Path $Target '.cockpit/state/doc-freshness-map.json') -Encoding utf8 -Value (@"
{
  "map_id": "doc-freshness-v1",
  "title": "Stale-docs rules (starter, adjustable)",
  "plain_language": {
    "what_this_is": "If this kind of code changed, this doc should have been updated too. Start small; grow from real misses.",
    "how_it_reads": "If code matching when_changed changed but expect_updated did not, stale-docs flags it. No rule match = stays quiet."
  },
  "compare_baseline": "pcc-baseline",
  "rules": [
    { "id": "app-in-brief", "when_changed": ["app/*.js"], "expect_updated": ["PROJECT.md"], "satisfied_by": "any", "why": "A user-facing app change should be reflected in the brief." }
  ],
  "not_yet_automated": [],
  "updated_at": "$stamp"
}
"@)

# Product-scoped bloat thresholds (soak fix F10). source_globs target THIS project's
# own product code; exclude_globs skip the copied PCC engine and vendored deps, so the
# owner never gets a bloat warning about app/renderer.js (PCC's tool, not their product).
Set-Content -LiteralPath (Join-Path $Target '.cockpit/state/bloat-thresholds.json') -Encoding utf8 -Value (@"
{
  "thresholds_id": "bloat-v1",
  "title": "Project-bloat thresholds (your product only, adjustable)",
  "plain_language": {
    "what_this_is": "Objective size/count signs of bloat in YOUR product's code. The copied PCC cockpit engine (app/, scripts/, schemas/) is deliberately excluded -- that's the tool that runs this project, not the product you're building.",
    "adjustable": "Add source_globs as your product's languages/areas appear; raise the limits deliberately if growth is legitimate."
  },
  "compare_baseline": "pcc-baseline",
  "max_source_file_lines": 600,
  "max_dependencies": 30,
  "source_globs": ["product/**.js", "product/**.mjs", "product/**.ts", "product/**.jsx", "product/**.tsx", "product/**.py", "product/**.rb", "product/**.go", "product/**.cs", "product/**.java", "product/**.html", "product/**.css"],
  "exclude_globs": ["**node_modules**", "**package-lock.json", "app/**", "scripts/**", "schemas/**", ".github/**", ".githooks/**"],
  "dependency_manifests": ["product/package.json"],
  "updated_at": "$stamp"
}
"@)

# Declared product run/verify commands (soak fix F3/F4). "Run the product" and
# "Verify product behavior" execute THESE, so the owner never types terminal commands
# and PCC never guesses how to run the product. Defaults assume the common product/
# layout; edit them to match how this product actually runs and tests.
Set-Content -LiteralPath (Join-Path $Target '.cockpit/state/product-run.json') -Encoding utf8 -Value (@"
{
  "config_id": "product-run-v1",
  "plain_language": {
    "what_this_is": "How to run and how to test YOUR product, declared once. The cockpit's 'Run the product' and 'Verify product behavior' buttons use these — no terminal needed.",
    "verify_note": "'verify' should run the product's own automated checks. A pass is recorded as a 'local_execution' proof (real execution on this machine, honestly not a clean-room CI run)."
  },
  "run": "npm start --prefix product",
  "verify": "npm test --prefix product",
  "cwd": ".",
  "updated_at": "$stamp"
}
"@)

# Backup tier (owner policy 2026-07-09: projects EARN off-machine backup). A fresh project has just
# been git-inited with NO remote, so it is born LOCAL-ONLY: local commits are the accepted
# checkpoint and the app shows a clean "Local checkpointed" instead of nagging about a missing
# remote or a false "Push FAILED". Change to "remote-backed" once the project earns an off-machine
# repo. (Fix for under-provisioning: children were born WITHOUT this file and sat in the undecided
# "setup" state instead of a clean local-only tier.)
Set-Content -LiteralPath (Join-Path $Target '.cockpit/state/backup-policy.json') -Encoding utf8 -Value (@"
{
  "config_id": "backup-policy-v1",
  "plain_language": {
    "what_this_is": "Which backup tier this project is on. 'local-only' means your local commits ARE the accepted checkpoint -- the app shows a clean 'Local checkpointed' and never nags about a missing remote. A new project starts here because it has no off-machine remote yet.",
    "how_to_upgrade": "When this project earns off-machine backup (you push it to a GitHub/remote repo), change mode to 'remote-backed' so the Backup button pushes and a push failure is treated as a real warning."
  },
  "mode": "local-only",
  "updated_at": "$stamp"
}
"@)

# High-stakes rules (declared boundary for the high-stakes signal). Missing = the detector honestly
# reports "unknown"; born with a starter list = it works from day one. Baseline is the bootstrap tag
# (pcc-baseline), matching the other generated boundaries. Globs are generic files every project has.
# (Fix for under-provisioning: children were born WITHOUT this file, so the high-stakes signal read
# "unknown" instead of watching the obvious high-stakes files.)
Set-Content -LiteralPath (Join-Path $Target '.cockpit/state/high-stakes-rules.json') -Encoding utf8 -Value (@"
{
  "_plain_language": "A DECLARED list of changes important enough that a second opinion (Codex cross-check) is worth considering before you rely on them. A match raises a 'consider a second opinion' notice in Signals; it never blocks anything. Edit deliberately -- the detector checks exactly this list and reports 'unknown' rather than guessing if it is missing.",
  "compare_baseline": "pcc-baseline",
  "high_stakes_globs": [
    "docs/DECISIONS.md",
    "CLAUDE.md",
    "AGENTS.md",
    "PROJECT.md",
    ".cockpit/state/app-build-scope.json",
    ".cockpit/state/doc-freshness-map.json",
    ".cockpit/state/lifecycle-model.json",
    ".cockpit/state/high-stakes-rules.json",
    "scripts/backup-protected-files.ps1",
    ".githooks/**"
  ],
  "flag_deletions": true
}
"@)

# --- vision promises (owner intent for the Owner Overview, DECISION-107). NEVER
#     copy PCC's own promises; generate FRESH per project. Use blueprint promises
#     only if the intake supplied owner-approved ones; otherwise a clearly-incomplete
#     placeholder that says it needs owner review. We never invent final promises. ---
$promises = $null
if ($bp -and $bp.vision_promises) { $promises = @($bp.vision_promises) }
if (-not $promises -or $promises.Count -eq 0) {
  $promises = @(
    [ordered]@{ id = 'primary-outcome'; label = "(Define $Name's primary outcome)"; declared_status = 'needs_owner_review'; evidence = ''; not_proven = 'Vision promises have not been reviewed by the owner yet.' }
  )
}
$visionObj = [ordered]@{
  version       = 1
  project       = $Name
  last_reviewed = $null
  review_status = 'needs_owner_review'
  note          = 'Owner-declared project intent, shown as cards in the Owner Overview. PLACEHOLDER until the owner reviews/replaces them. declared_status is self-assessment, not machine proof.'
  promises      = $promises
}
Set-Content -LiteralPath (Join-Path $Target '.cockpit/state/vision-promises.json') -Encoding utf8 -Value ($visionObj | ConvertTo-Json -Depth 6)

# --- 5. starter docs (filled from the blueprint when present) ---
Ensure-Dir (Join-Path $Target 'docs')

function BpList($arr) { if ($arr) { return (($arr | ForEach-Object { "- $_" }) -join "`n") } return '' }

if ($bp -and $bp.project) {
  $p = $bp.project
  $whatThis = "$Name — $($p.problem_statement)`n`nFor: $($p.target_user)`n`nDone looks like: $($p.desired_outcome)"
  if ($p.hard_constraints) { $whatThis += "`n`nHard constraints: $($p.hard_constraints)" }
  $inScope = BpList $bp.scope.in_scope
  $outScope = BpList $bp.scope.out_of_scope
  $riskLines = ''
  if ($bp.scope.risks) { $riskLines = (($bp.scope.risks | ForEach-Object { "- [$($_.severity)] $($_.description) -> $($_.mitigation)" }) -join "`n") }
  $scopeBlock = "`n`n## Scope`n**In:**`n$inScope`n`n**Out:**`n$outScope"
  if ($riskLines) { $scopeBlock += "`n`n**Risks:**`n$riskLines" }
  $decisionBody = "Project defined via the PCC chat intake. Problem: $($p.problem_statement) Outcome: $($p.desired_outcome) Risk tolerance: $($p.risk_tolerance). Check-in: $($p.preferred_stopping_point)."
} else {
  $whatThis = "$Name. (Define the goal and what ""done"" looks like here.)"
  $scopeBlock = ''
  $decisionBody = "This project was scaffolded from the PCC reference implementation: cockpit app, deterministic detectors, lifecycle state-machine, and honest-signal design."
}

Set-Content -LiteralPath (Join-Path $Target 'PROJECT.md') -Encoding utf8 -Value (@"
# PROJECT.md - current project brief

Read this first. Always-current summary so a new session starts fully oriented.

## What this is
$whatThis$scopeBlock

## Owner
Visionary / product lead. Plain-language, concise, no cheerleading, no fake "done".
Standing rules are in CLAUDE.md.

## Where we are
- Phase: define (just bootstrapped). Lifecycle map is in the app's Lifecycle tab.
- Next: define the goal and rough scope, then plan the first bounded task.

## How this project is run (PCC cockpit)
- Launch the app: npm install --prefix app (once), then npm start --prefix app.
- Signals tab watches for untracked files, drift, stale docs, un-backed-up work,
  bloat, and sycophancy. Lifecycle tab shows the stage map. Project tab generates
  a new-chat handoff and shows recent decisions.
- Detectors are deterministic scripts in scripts/; the app just consumes them.

## Key decisions
- See docs/DECISIONS.md.
"@)

Set-Content -LiteralPath (Join-Path $Target 'docs/DECISIONS.md') -Encoding utf8 -Value (@"
# Decisions log

> New decisions are recorded as MADR ADRs in ``docs/adr/`` (enforced by
> ``scripts/check-adr.ps1``, gated in CI + pre-commit). See
> ``docs/DECISION_AND_CHANGE_STANDARD.md``. This file is a legacy archive kept only for
> the bootstrap record below.

## DECISION-001: $Name defined and bootstrapped with the PCC cockpit
Date: $stamp
Status: Active

$decisionBody
"@)

# The decision standard travels as an enforced format: seed the ADR directory with a
# well-formed starter (docs/adr/0000) so check-adr.ps1 validates a real record from day
# one and the format is exemplified for the owner's first real decision.
Ensure-Dir (Join-Path $Target 'docs/adr')
Set-Content -LiteralPath (Join-Path $Target 'docs/adr/0000-record-decisions-as-adrs.md') -Encoding utf8 -Value (@"
---
status: Accepted
date: $(Get-Date -Format 'yyyy-MM-dd')
deciders: owner
---

# ADR-0000: Record decisions as MADR ADRs, enforced by a validator

## Context and Problem
This project inherits PCC's decision standard: significant decisions must be recorded in one
machine-checkable format so they cannot be recorded wrong, and a new session can find just the
record it needs instead of relying on discipline.

## Decision
Record significant decisions (architecture, scope, workflow, verification, owner expectations)
as MADR ADRs, one file per decision at ``docs/adr/NNNN-kebab-title.md``, with YAML front matter
(status, date) and the sections below. New decisions go here, not the legacy docs/DECISIONS.md.

## Consequences
One enforced, findable decision format from day one; a small amount of ceremony per decision.

## Confirmation
``scripts/check-adr.ps1`` validates every ``docs/adr/*.md`` (front matter + the five required
sections, incl. Confirmation and Engagement) and is gated in ``.github/workflows/ci.yml`` and
``.githooks/pre-commit`` — both inherited from the cockpit engine.

## Engagement
- Worker/verifier: the ADR policy is in AGENTS.md ("check docs/adr/ before deciding").
- Standard + template: ``docs/DECISION_AND_CHANGE_STANDARD.md``.
- Future chats: ``docs/adr/`` is the decision store.

## Supersedes / Related
Related: docs/DECISION_AND_CHANGE_STANDARD.md, docs/specs/README.md, docs/TRUST_CALIBRATION.md.
"@)
Write-Output "  + docs/adr/0000-record-decisions-as-adrs.md (starter)"

# --- 6. git init ---
if (-not $NoGit) {
  Push-Location $Target
  try {
    & git init | Out-Null
    & git add -A | Out-Null
    # --no-verify: the pre-commit test gate now travels (.githooks/), but the new
    # project's node_modules isn't installed yet, so this first scaffold commit
    # must not be gated. The gate activates for the owner's real commits once they
    # run `npm install --prefix app` (postinstall wires core.hooksPath).
    & git -c user.name='PCC Bootstrap' -c user.email='pcc@localhost' commit -q --no-verify -m "Bootstrap $Name from PCC" | Out-Null
    # Tag the bootstrap commit as the drift/stale-docs baseline (soak fix F9). A
    # fresh project has no 'main' branch, so the detectors' baseline must be a ref
    # that actually exists. A tag is stable, branch-name-independent, and marks
    # exactly "the point the owner's work started from" -- so drift compares
    # everything built since bootstrap, not an incomplete working-tree-only diff.
    & git tag pcc-baseline | Out-Null
    Write-Output "git: initialized, made the first commit, and tagged it 'pcc-baseline' (drift/stale-docs baseline)."
  } catch { Write-Output "git: skipped ($($_.Exception.Message))" }
  Pop-Location
}

# --- register with the home cockpit (file bridge) ---
# Drop the new project's path into an inbox in the repo this script was launched
# from, so the running cockpit auto-imports it into its project switcher (the app
# clears the inbox after reading). This is what makes "New project" appear in the
# switcher without a manual "Open existing project" step. -NoInbox skips this when the caller
# (e.g. the DECISION-114 Save Project flow) registers the new project directly.
if (-not $NoInbox) {
  try {
    $inboxPath = Join-Path $src '.cockpit/state/scaffolded-inbox.json'
    $inbox = @()
    if (Test-Path -LiteralPath $inboxPath) { try { $inbox = @(Get-Content -Raw -LiteralPath $inboxPath | ConvertFrom-Json) } catch { $inbox = @() } }
    if ($inbox -notcontains $Target) { $inbox += $Target }
    ($inbox | ConvertTo-Json -AsArray) | Out-File -FilePath $inboxPath -Encoding utf8
  } catch { }
}

Write-Output ''
Write-Output "Done. Next steps:"
Write-Output "  1. Back in the cockpit, open the project switcher — '$Name' will be there."
Write-Output "  2. Or from a terminal: npm start --prefix `"$Target\app`"."
Write-Output "  3. Fill in PROJECT.md's goal, then use the Lifecycle tab to move from 'define' to 'plan'."
